import { 
    Home,
    Assignment,
    Feedback,
    Business,
    HealthAndSafety,
    Person,
    LocalHospital,
    Description,
    Email,
    Chat,
    AccessTime,
    LocationOn,
    CalendarToday,
    ArrowBackIos,
    ArrowForwardIos,
    AssignmentInd,
    TableChart,
    ContentPasteSearch,
    ContentCopy,
    Help,
    AccountCircle
} from '@mui/icons-material';

const Icons = {
    Home: <Home />,
    Assignment: <Assignment />,
    Feedback: <Feedback />,
    Business: <Business />,
    HealthAndSafety: <HealthAndSafety />,
    Person: <Person />,
    LocalHospital: <LocalHospital />,
    Description: <Description />,
    Email: <Email />,
    Chat: <Chat />,
    AccessTime: <AccessTime />,
    LocationOn: <LocationOn fontSize="small" color="disabled" />,
    CalendarToday: <CalendarToday fontSize="small" color="disabled"/>,
    ArrowBackIos: <ArrowBackIos />,
    ArrowForwardIos: <ArrowForwardIos />,
    AssignmentInd: <AssignmentInd />,
    TableChart: <TableChart />,
    ContentPasteSearch: <ContentPasteSearch />,
    ContentCopy: <ContentCopy />,
    Help: <Help />,
    AccountCircle: <AccountCircle />,
};

export default Icons;